---
version: '3'
services:
  web:
    build: ./web
    ports:
      - 8080:8080
  api:
    build: ./api
    ports:
      - 8081:8080
    depends_on:
      - dbs
  dbs:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
